apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SECRET_KEY: QDc5OGg1YXFfMmo1NWJ0Xjd6ayV1JjdxNDIwMHZwYjIzNHFtKD1keHZqbzMrdW0=
  TRADIER_API_KEY: U05jc1RidmZmYm5MN0tyZTdLOUZEUnpOQUxqdg==
  EMAIL_HOST_PASSWORD: U0cubHdodGN2a19UQWlVQ2NYQ21jZ09hQS5hYUo1N0VaVkg5OTJUUm90YWI1TjlxbnNOSVdMVDk5aHdnY1RMeVRjdjRR
