apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    role: web
    dns: route53
  annotations:
    domainName: "visual-option-chain-graph.com"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: django
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer
