apiVersion: v1
kind: Service
metadata:
  name: kubernetes-django-service
spec:
  selector:
    app: kubernetes-django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
