dist: bionic
os: linux
language: python

python:
  - "3.6"

services:
  - postgresql
  - docker
  - redis-server

env:
  global:
    - PGPORT=5432
    - PGUSER=postgres
    - DJANGO_VERSION=2.2.15
    - DOCKER_COMPOSE_VERSION=1.25.5
    - TRAVIS=True

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  - sudo apt-get update
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
  - sudo service redis-server stop
  - sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'secret'

script:
  - python manage.py test

after_success:
  - docker ps
  - docker images
  - docker build -t visual-option-chain-graph .
  - docker-compose down
  - docker-compose up -d
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag visual-option-chain-graph willwcchan/visual-option-chain-graph:latest
  - docker push willwcchan/visual-option-chain-graph:latest
