dist: bionic
os: linux
language: python

python:
  - "3.6"

services:
  - postgresql
  - docker

env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
  - DJANGO_VERSION=2.2.15

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  - sudo apt-get update
  - pip install -r requirements.txt 
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test
  - docker-compose down
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag visual-option-chain_graph willwcchan/visual-option-chain_graph:latest
  - docker push willwcchan/visual-option-chain_graph:latest

# https://docs.travis-ci.com/user/docker/
before_install:
  - docker-compose up
  