dist: bionic
os: linux
language: python
cache: pip

python:
  - "3.6"

services:
  # - postgresql
  - docker

env:
  global:
    # - PGPORT=5432
    # - PGUSER=postgres
    - DJANGO_VERSION=2.2.15
    - DOCKER_COMPOSE_VERSION=1.25.5

# addons:
#   postgresql: "10"
#   apt:
#     packages:
#       - postgresql-10
#       - postgresql-client-10

before_script:
  - sudo apt-get update
  - pip install -r requirements.txt

script:
  - docker build -t visual-option-chain-graph .
  - docker-compose up -d
  - docker images
  - python manage.py makemigrations
  - python manage.py migrate
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag visual-option-chain-graph willwcchan/visual-option-chain-graph:latest
  - docker push willwcchan/visual-option-chain-graph:latest
