dist: bionic
os: linux
language: python

python:
  - "3.6"

services:
  - postgresql

env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
  - DJANGO_VERSION=2.2.15

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  - sudo apt-get update
  - psql -d postgres -U postgres
  - pip install -r requirements.txt 
  - python manage.py makemigrations
  - python manage.py migrate

script:
  # - docker-compose run web python manage.py test
  - python manage.py test