dist: bionic
os: linux
language: python

python:
  - "3.6"

services:
  - postgresql
  - docker

env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
  - DJANGO_VERSION=2.2.15
  - DOCKER_COMPOSE_VERSION=1.25.5

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_install:
  - docker-compose down
  - docker built --tag visual-option-chain-graph_web/latest .
  - docker images

before_script:
  - sudo apt-get update
  - pip install -r requirements.txt 
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test

after_success:
  - docker-compose up 
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag visual-option-chain-graph_web willwcchan/visual-option-chain-graph_web:latest
  - docker push willwcchan/visual-option-chain-graph_web:latest
  