dist: xenial
os: linux
language: python

python:
  - "3.7"

services:
  - postgresql

env:
  DJANGO_VERSION=2.2.15

addons:
  postgresql: "12"

before_script:
  - virtualenv env
  - source env/bin/activate
  - pip install -r requirements.txt 
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test