dist:xenial
os:linux
language: python

python:
  - "3.5"

# setup environment
env:
  - DJANGO_VERSION=2.2.15

# install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - pwd
  - virtualenv env
  - source env/bin/activate
  - pip install -r requirements.txt

# run test scripts
script:
  - python manage.py makemigrations optionchain
  - python manage.py migrate
  - python manage.py test


notifications:
  slack:
    rooms:
	  - willchan:96CjJeUdPsiIh7Y8b7Z6QWis#general
	  - willchan:96CjJeUdPsiIh7Y8b7Z6QWis#random
    