version: "3.7"

#https://docs.docker.com/compose/django/
services:
    db:
        image: postgres:10
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"

    redis:
        hostname: redis
        image: "redis:alpine"
        ports:
            - "6379:6379"

    # https://blog.agchapman.com/using-variables-in-docker-compose-files/
    web:
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - TRADIER_API_KEY=${TRADIER_API_KEY}
        build:
            context: .
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis

    celery:
        build: .
        environment:
            - SECRET_KEY=${SECRET_KEY}
            - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
            - TRADIER_API_KEY=${TRADIER_API_KEY}
        command: celery -A visual-option-chain worker -l info -E
        volumes:
            - .:/code
        depends_on:
            - redis

volumes:
    postgres_data:
