# Generated by Django 3.0.8 on 2020-08-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrinio_code', models.CharField(max_length=30, null=True)),
                ('expiration', models.DateField()),
                ('intrinio_id', models.CharField(max_length=20, null=True)),
                ('strike', models.FloatField(default=0.0)),
                ('ticker', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='OptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', models.FloatField(default=0.0)),
                ('close_ask', models.FloatField(default=0.0)),
                ('close_bid', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('delta', models.FloatField(default=None)),
                ('implied_volatility', models.FloatField(default=None)),
                ('implied_volatility_change', models.FloatField(default=None)),
                ('next_day_open_interest', models.IntegerField(default=0)),
                ('open_interest', models.IntegerField(default=0)),
                ('open_interest_change', models.IntegerField(default=0)),
                ('trades', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('volume_ask', models.IntegerField(default=0)),
                ('volume_bid', models.IntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optionchain.Option')),
            ],
        ),
    ]
