# Generated by Django 3.0.8 on 2020-08-12 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, null=True)),
                ('expiration', models.DateField()),
                ('strike', models.FloatField(default=0.0)),
                ('ticker', models.CharField(max_length=8)),
                ('type', models.CharField(max_length=4)),
                ('expiration_type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='OptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', models.FloatField(default=0.0, null=True)),
                ('close_ask', models.FloatField(default=0.0)),
                ('close_bid', models.FloatField(default=0.0)),
                ('delta', models.FloatField(default=None, null=True)),
                ('implied_volatility', models.FloatField(default=None, null=True)),
                ('open_interest', models.IntegerField(default=0)),
                ('trades', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('volume_ask', models.IntegerField(default=0)),
                ('volume_bid', models.IntegerField(default=0)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optionchain.Option')),
            ],
        ),
    ]
