# Generated by Django 3.0.8 on 2020-08-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionprice',
            name='delta',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optionprice',
            name='implied_volatility',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optionprice',
            name='implied_volatility_change',
            field=models.FloatField(default=None, null=True),
        ),
    ]
