# Generated by Django 3.0.8 on 2020-08-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optionchain', '0002_auto_20200807_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionprice',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optionchain.Option'),
        ),
    ]
