# Generated by Django 3.0.8 on 2020-08-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optionchain', '0003_auto_20200811_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='intrinio_id',
        ),
        migrations.RemoveField(
            model_name='optionprice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='optionprice',
            name='implied_volatility_change',
        ),
        migrations.RemoveField(
            model_name='optionprice',
            name='next_day_open_interest',
        ),
        migrations.RemoveField(
            model_name='optionprice',
            name='open_interest_change',
        ),
    ]
