# Generated by Django 3.0.8 on 2020-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionchain', '0004_auto_20200812_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionprice',
            name='close',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
